name: "Enter Nix dev-shell"
description: "Enters a Nix dev-shell"

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31

    - name: Verify flake integrity
      run: nix flake check

    - name: Enter Nix dev-shell
      run: nix develop
