name: Build (Linux, x86-64)

# TODO: test with only pull-request
on:
<<<<<<< HEAD
  push:
    paths: &workflow_paths
      - "**.cppm"
      - "**.ixx"
      - "**.inl"
      - "**.mpp"
      - "**.ipp"
      - "**.tpp"
      - "**.txx"
      - "**.inc"
      - "**.c++"
      - "**.h++"
      - "**.cpp"
      - "**.hpp"
      - "**.cxx"
      - "**.hxx"
      - "**.cc"
      - "**.hh"
      - "**.c"
      - "**.h"
      - ".github/workflows/build-linux.yml"
      - "**/meson.build"
      - "flake.nix"

  pull_request:
    paths: *workflow_paths

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'dev/') }}

env:
  CCACHE_DIR: ${{ runner.temp }}/ccache

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'dev/') }}

jobs:
  build-linux-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Enter dev-shell
        uses: ./.github/workflows/composite/enter-devshell.yml

      - name: Restore build cache
        uses: ./.github/workflows/composite/restore-cache.yml
        with:
          ccache_dir: env.CCACHE_DIR

      - name: Build meson (release)
        uses: ./.github/workflows/composite/build-meson.yml
        with:
          dir_name: "build_release"
          setup_args: "--buildtype=release"

  build-linux-debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Enter dev-shell
        uses: ./.github/workflows/composite/enter-devshell.yml

      - name: Restore build cache
        uses: ./.github/workflows/composite/restore-cache.yml
        with:
          ccache_dir: env.CCACHE_DIR

      - name: Build meson (debug)
        uses: ./.github/workflows/composite/build-meson.yml
        with:
          dir_name: "build_debug"
          setup_args: "--buildtype=debug"
